#!/usr/bin/env ruby

require 'optparse'
require 'pathname'
$LOAD_PATH.unshift(
  File.expand_path('../../lib', Pathname.new(__FILE__).realpath))

require 'erb_asterisk'
require 'erb_asterisk/arg_parser'

arg_parser = ErbAsterisk::ArgParser.new

include ErbAsterisk
execute(arg_parser.execute)
